services:
  - type: web
    name: tamilnadu-electronics
    env: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /assets/images/*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
